version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'app'
  keycloak-postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: dev
      DB_SCHEMA: public
      DB_PASSWORD: pwd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: change_me
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8180:8080"
    depends_on:
      - keycloak-postgres
  client-ui:
    image: muravevartem/samokatim-client-ui:latest
    ports:
      - '80:80'
      - '443:443'
  gateway:
    image: muravevartem/samokatim-gateway:latest
    ports:
      - '8080:8080'
  monitoring-service:
    image: muravevartem/samokatim-monitoring-service:latest
  handbook-service:
    image: muravevartem/samokatim-handbook-service:latest
