version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'app'
  keycloak-postgres:
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5433"
  keycloak:
    image: "jboss/keycloak:15.0.2"
    depends_on:
      - "keycloak-postgres"
    env_file:
      - ./keycloak.dev.env
    ports:
      - "8180:8180"
      - "8787:8787"
  client-ui:
    image: muravevartem/samokatim-client-ui:latest
    ports:
      - '80:80'
      - '443:443'
  gateway:
    image: muravevartem/samokatim-gateway:latest
    ports:
      - '8080:8080'
  monitoring-service:
    image: muravevartem/samokatim-monitoring-service:latest
  handbook-service:
    image: muravevartem/samokatim-handbook-service:latest
